### PR TITLE
les: les4 PR proposed changes part 2

### PR DESCRIPTION
**Pull request by rjl493456442**
This PR rewrites lots of components introduced by les4 PR.

The most important parts are:

- rewrite expired value
  Originally the code is quite confused. We have cumulative running time to act as the expiration. 
  However, in order to ensure that the accuracy is not lost, the original code uses a constant with
  a large value and divide the offset when we finally try to calculate the value.

  Now it's converted to float64, which can ensure the accuracy is not lost and avoid numerically
  conversion

- rework clientdb, redefine tokenBalance, currencyBalance
  Originally we have postive balance, negative balance definition. The first change is to separate `currencyBalance` from positive balance. The reason is `currencyBalance` is permanent, while token balance is volatile. If we mix the currency balance with the token balance, we cannot delete the entry directly when the token balance is 0. And also currency balance retrieval is hard.

  The seond change is uniform the token balance. Now the positive balance and negative balance actually is totally the same expect the key is `enode.ID` and `ip_address`. There is no reason we have two definitions for them. So `tokenBalance` is enough.

  The third change is using tableDatabase to take care the db version. It's more clean but wait a PR to fix the bug of tableDatabase

- introduce activate and deactivate notion to balanceTracker
  Now each connected client has two modes: inactive and active. Originally we handle these two status via setting different `priceFactors` to tracker. It's buggy. 

  - Like if we want to calculate the missing positive balance with an inactive tracker, the factors are zero 
  but it's not what we want.

  - Like if we want to calculate the missing positive balance with a different target capacity, the factors should be recalculated.

  So I move all priceFactor notions into the balanceTracker and add a new field `active`.

- rework the clientpool
  clientpool is super complicated now. We need to handle lots of corner cases. We need to handle lots of status like `priority`, `active`, `connected` etc.

  So lots of code are added to make the logic clean.

### CODE REVIEW

**Comment by zsfelfoldi** [comment]
This PR-on-a-PR method is good but maybe we should do it in multiple steps. The first 4 commits are not extremely complicated and I like most of these changes. I have suggestions for the first two, I'll write separate comments for them so that we can discuss further there.

**Comment by zsfelfoldi** [comment]
About "les: rework expired value":
Using `expiredValue` for `negBalance` is a logical change because it makes the logic easier to understand. Adding a test is also very good. What I don't like here is changing the format of logarithms to `float64` from fixed-point `uint64`. These logarithmic offsets are accumulated over time and floats just lose precision over time if many small values are added. The "beauty" of the code is a bit subjective and maybe I am more attracted to fixed point format than others :) But objectively what happens here is that we lose 16 bits of precision for no good reason. The calculations need some explanation anyway so I don't think it's a lot simpler either. With fixed point arithmetics we lose way less information because we subtract the high part of `logOffset` from the exponent and only then convert it to floating point. Subtracting two big floating point numbers whose difference is small is something you should always avoid (that is one of the two most important caveats with floating point arithmetics, the other is adding lots of small values sequentially, which your version also does when accumulating `logOffset`).

**Comment by zsfelfoldi** [comment]
About "les: rework client db":
Separating and adding a test for the client db is good. Moving `pcBalance` (or `currencyBalance`) up from the `meta` field to the "top level" is maybe easier to handle and I can accept this change. The problem is that you got rid of the `receiverMeta` fields too and there is no replacement solution. I mean we can do it some other way, I am not very committed to these `meta` fields, maybe they are weird or ugly :) But we need some way to do safe atomic transactions and avoid the balance database and the payment receiver going out of sync. We should never modify just a single value here (except when spending/expiring `tokenBalance`). The token sale modifies `tokenBalance` and `currencyBalance` together. The payment receiver adds to `currencyBalance` and also needs to remember the total amount of the last processed cheque and these two should also change together atomically.

I've been thinking and maybe what we could do is to make the client database a key/value store that allows atomic operations. Then we would not need this weird hierarchical encoding scheme and maybe further upgrades would be easier too. We have two kinds of balances associated with `nodeID` already, `positiveBalance` ("pb") and `currencyBalance` ("cb"). The lottery book could use a third entry ("lotteryBook/lastCheque" or just "lb/lc" to save space) for the total amount of last processed cheque and update it atomically with `currencyBalance`. So the payment receiver module of the lottery book could get read/write access to all client fields under the "lb/" prefix. Writes would be committed in a single batch, together with the `currencyBalance` update.
One of your issues with the first scheme was that we cannot remove expired token balance entries separately because they are mixed together. With this scheme they are not, "nodeID:pb" can be deleted independently from "nodeID:cb". Basically the only thing we need to add to your current version is some locking mechanism per `nodeID` that allows reading some keys and creating a batch of writes without another process accessing the keys under the same `nodeID` at the same time. I would also suggest using these keys as suffixes after `nodeID` (like in my example) instead of prefixes (as it is currently implemented) to make it easier to list all keys belonging to a `nodeID`.

Now that I think about it, this is something I could easily do starting with your version so if you agree then we can merge this commit as is and I will add the atomic mechanism after. I could do it right now but I do not want to open a PR on your PR on a PR :)

**Comment by rjl493456442** [comment]
@zsfelfoldi I think about the second issue: `the atomicity of currency balance updating`, I agree there is an atomicity issue. But probably I will leave it now.

The reason is: I think the notion of `currency balance` probably should be attached with `clientdb`. ClientDB is mainly designed for recording the token balances of clients. `CurrencyBalance` should be handled in PaymentDB.

So if we move the currency balance into PaymentDB, then there is no atomicity issue anymore(I will handle it in my payment contract PR).

**Comment by rjl493456442** [comment]
@zsfelfoldi I rebase this PR, please check it again.

**Comment by zsfelfoldi** [comment]
Implementing a general-purpose atomic db is a great idea. The way it is implemented here might not fit our use case perfectly though. The problem is that the atomicity is required for each client separately while the data belonging to different clients might be accessed simultaneously. The way I would implement it is that opening a new "transaction" should not be a function of the atomic db but it should create an atomic "child database" that uses the parent db read functions for reading but puts every write/del operation into the batch. After finalizing the transaction the atomic child db could be discarded. This way mutexes are not needed and everything is inherently thread safe.

```
// read operations are performed on db.db
// write operations are performed on db.batch
type AtomicDatabase struct {
	db    ethdb.Database
	batch ethdb.Batch
}

func NewAtomicDatabase(parent ethdb.Database) *AtomicDatabase {
	return &AtomicDatabase{parent, parent.NewBatch()}
}

func (db *AtomicDatabase) Finalize() {
	db.batch.Write()
}
```

If you want to implement this then please open a separate PR because it can be merged easily while the client pool changes are more complex.

**Comment by zsfelfoldi** [comment]
About the client pool rework: understanding this part of the code was probably a lot of work for you and your changes show that you really went into the details. It also took me several hours to understand your changes but now I have a much better understanding of which parts were messy and why. The activation/deactivation logic is nicely cleaned up in your version. Separating the `expirer` is also nice. There are lots of tiny changes touching sensitive parts though that are really hard to judge and some look a bit suspicious to me. What I realized while comparing the two versions is that there are just too many possible interactions between different mechanisms and either version would probably be a nightmare to maintain over the long term. Luckily now I also have an idea for some further refactoring that would break this complex logic up into smaller, more or less self-contained components that are easier to explain, understand and verify/test. So in the next iteration I would like to propose a client pool refactoring that is based both on my version and your changes. For the new server pool I wrote a nice little tool that greatly simplifies complex interactions between different peer mechanisms. The same idea (even the same component) can be reused here so that the active priority pool, the inactive queue and the balance mechanisms can be better separated and their possible interactions really simplified. I hope I can show it to you in a few days.

**Pull request closed without merging**
